"""Initial tables

Revision ID: 045144f94137
Revises: 
Create Date: 2026-03-21 22:05:09.994515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045144f94137'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sexenum'), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('identification_number', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('COMPANY', 'NON_PROFIT', 'GOVERNMENT', 'OTHER', name='organizationtypeenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'identification_number', name='uq_organization_name_identification_number')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('activation_code', sa.String(), nullable=True),
    sa.Column('issuer_organization_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['issuer_organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index('idx_cards_identity_id', 'cards', ['identity_id'], unique=False)
    op.create_index('idx_cards_issuer_organization_id', 'cards', ['issuer_organization_id'], unique=False)
    op.create_index('idx_cards_uid', 'cards', ['uid'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id', 'organization_id', name='uq_membership_identity_org')
    )
    op.create_index('idx_memberships_identity_id', 'memberships', ['identity_id'], unique=False)
    op.create_index('idx_memberships_organization_id', 'memberships', ['organization_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', name='uq_project_name_org_id')
    )
    op.create_index('idx_projects_organization_id', 'projects', ['organization_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sexenum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('birthday_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_table('access_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_access_tokens_expires_at', 'access_tokens', ['expires_at'], unique=False)
    op.create_index('idx_access_tokens_user_id', 'access_tokens', ['user_id'], unique=False)
    op.create_table('card_assignment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('identity_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_card_assignment_history_assigned_at', 'card_assignment_history', ['assigned_at'], unique=False)
    op.create_index('idx_card_assignment_history_card_id', 'card_assignment_history', ['card_id'], unique=False)
    op.create_index('idx_card_assignment_history_identity_id', 'card_assignment_history', ['identity_id'], unique=False)
    op.create_index('idx_card_assignment_history_unassigned_at', 'card_assignment_history', ['unassigned_at'], unique=False)
    op.create_index('uq_active_card_assignment', 'card_assignment_history', ['card_id'], unique=True, postgresql_where=sa.text('unassigned_at IS NULL'))
    op.create_table('identity_project_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id', 'project_id', name='uq_identity_project_permission')
    )
    op.create_index('idx_identity_project_permissions_identity_id', 'identity_project_permissions', ['identity_id'], unique=False)
    op.create_index('idx_identity_project_permissions_project_id', 'identity_project_permissions', ['project_id'], unique=False)
    op.create_table('readers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', name='uq_reader_name_org_id')
    )
    op.create_index('idx_readers_organization_id', 'readers', ['organization_id'], unique=False)
    op.create_index('idx_readers_project_id', 'readers', ['project_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('secret', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('reader_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('metadata_desc', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_card_id', 'events', ['card_id'], unique=False)
    op.create_index('idx_events_created_at', 'events', ['created_at'], unique=False)
    op.create_index('idx_events_project_id', 'events', ['project_id'], unique=False)
    op.create_index('idx_events_reader_id', 'events', ['reader_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_reader_id', table_name='events')
    op.drop_index('idx_events_project_id', table_name='events')
    op.drop_index('idx_events_created_at', table_name='events')
    op.drop_index('idx_events_card_id', table_name='events')
    op.drop_table('events')
    op.drop_table('webhooks')
    op.drop_table('user_roles')
    op.drop_table('user_permissions')
    op.drop_index('idx_readers_project_id', table_name='readers')
    op.drop_index('idx_readers_organization_id', table_name='readers')
    op.drop_table('readers')
    op.drop_index('idx_identity_project_permissions_project_id', table_name='identity_project_permissions')
    op.drop_index('idx_identity_project_permissions_identity_id', table_name='identity_project_permissions')
    op.drop_table('identity_project_permissions')
    op.drop_index('uq_active_card_assignment', table_name='card_assignment_history', postgresql_where=sa.text('unassigned_at IS NULL'))
    op.drop_index('idx_card_assignment_history_unassigned_at', table_name='card_assignment_history')
    op.drop_index('idx_card_assignment_history_identity_id', table_name='card_assignment_history')
    op.drop_index('idx_card_assignment_history_card_id', table_name='card_assignment_history')
    op.drop_index('idx_card_assignment_history_assigned_at', table_name='card_assignment_history')
    op.drop_table('card_assignment_history')
    op.drop_index('idx_access_tokens_user_id', table_name='access_tokens')
    op.drop_index('idx_access_tokens_expires_at', table_name='access_tokens')
    op.drop_table('access_tokens')
    op.drop_index('idx_users_organization_id', table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index('idx_projects_organization_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_memberships_organization_id', table_name='memberships')
    op.drop_index('idx_memberships_identity_id', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('idx_cards_uid', table_name='cards')
    op.drop_index('idx_cards_issuer_organization_id', table_name='cards')
    op.drop_index('idx_cards_identity_id', table_name='cards')
    op.drop_table('cards')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('organizations')
    op.drop_table('identities')
    # ### end Alembic commands ###
