"""Alter Events table

Revision ID: 148338277cd3
Revises: ee46c982c3b9
Create Date: 2026-03-20 10:30:18.734063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '148338277cd3'
down_revision: Union[str, Sequence[str], None] = 'ee46c982c3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('metadata_desc', sa.JSON(), nullable=True))
    op.drop_index(op.f('idx_events_identity_id'), table_name='events')
    op.drop_index(op.f('idx_events_type'), table_name='events')
    op.create_index('idx_events_reader_id', 'events', ['reader_id'], unique=False)
    op.drop_constraint(op.f('events_identity_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_admin_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'type')
    op.drop_column('events', 'metadata')
    op.drop_column('events', 'admin_id')
    op.drop_column('events', 'identity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('identity_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('type', sa.VARCHAR(length=18), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('events_admin_id_fkey'), 'events', 'users', ['admin_id'], ['id'])
    op.create_foreign_key(op.f('events_identity_id_fkey'), 'events', 'identities', ['identity_id'], ['id'])
    op.drop_index('idx_events_reader_id', table_name='events')
    op.create_index(op.f('idx_events_type'), 'events', ['type'], unique=False)
    op.create_index(op.f('idx_events_identity_id'), 'events', ['identity_id'], unique=False)
    op.drop_column('events', 'metadata_desc')
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ###
