"""Change Card Status in Enum

Revision ID: 8ee8fa9097c7
Revises: ee46c982c3b9
Create Date: 2026-03-20 05:27:16.477833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee8fa9097c7'
down_revision: Union[str, Sequence[str], None] = 'ee46c982c3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'REVOKED', 'PENDING', 'BLOCKED', 'LOST', 'STOLEN', 'DAMAGED', name='cardstatusenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'REVOKED', 'PENDING', 'BLOCKED', 'LOST', 'STOLEN', 'DAMAGED', name='cardstatusenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
