"""Models revision

Revision ID: a2481787488e
Revises: e310e33bd31d
Create Date: 2026-03-20 03:33:08.822382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2481787488e'
down_revision: Union[str, Sequence[str], None] = 'e310e33bd31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tokens', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('card_assignment_history', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('cards', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('identities', sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sexenum'), nullable=True))
    op.add_column('identities', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('identities', sa.Column('address', sa.String(), nullable=True))
    op.add_column('identities', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('identities', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('identity_project_permissions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('identity_project_permissions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('memberships', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('readers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('readers', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('uq_reader_name_org_id', 'readers', ['name', 'organization_id'])
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('roles', 'updated_at')
    op.drop_constraint('uq_reader_name_org_id', 'readers', type_='unique')
    op.drop_column('readers', 'updated_at')
    op.drop_column('readers', 'created_at')
    op.drop_column('projects', 'updated_at')
    op.drop_column('permissions', 'updated_at')
    op.drop_column('organizations', 'updated_at')
    op.drop_column('memberships', 'updated_at')
    op.drop_column('identity_project_permissions', 'updated_at')
    op.drop_column('identity_project_permissions', 'created_at')
    op.drop_column('identities', 'updated_at')
    op.drop_column('identities', 'date_of_birth')
    op.drop_column('identities', 'address')
    op.drop_column('identities', 'phone')
    op.drop_column('identities', 'sex')
    op.drop_column('events', 'updated_at')
    op.drop_column('cards', 'updated_at')
    op.drop_column('card_assignment_history', 'updated_at')
    op.drop_column('access_tokens', 'updated_at')
    # ### end Alembic commands ###
