"""Add updated_at to Webhook Table

Revision ID: dcc559d1b322
Revises: 3489c3ad91d0
Create Date: 2026-03-21 18:01:04.043007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc559d1b322'
down_revision: Union[str, Sequence[str], None] = '3489c3ad91d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'updated_at')
    # ### end Alembic commands ###
