"""More table constraints

Revision ID: ee46c982c3b9
Revises: efc7feee30e7
Create Date: 2026-03-20 04:46:24.082385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee46c982c3b9'
down_revision: Union[str, Sequence[str], None] = 'efc7feee30e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'identification_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'identification_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
