"""More table constraints

Revision ID: efc7feee30e7
Revises: a2481787488e
Create Date: 2026-03-20 04:44:11.533527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc7feee30e7'
down_revision: Union[str, Sequence[str], None] = 'a2481787488e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_card_assignment', 'card_assignment_history', ['card_id'], unique=True, postgresql_where=sa.text('unassigned_at IS NULL'))
    op.create_unique_constraint('uq_identity_project_permission', 'identity_project_permissions', ['identity_id', 'project_id'])
    op.create_unique_constraint('uq_membership_identity_org', 'memberships', ['identity_id', 'organization_id'])
    op.add_column('organizations', sa.Column('identification_number', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('url', sa.String(), nullable=True))
    op.create_unique_constraint('uq_organization_name_identification_number', 'organizations', ['name', 'identification_number'])
    op.create_unique_constraint('uq_project_name_org_id', 'projects', ['name', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_name_org_id', 'projects', type_='unique')
    op.drop_constraint('uq_organization_name_identification_number', 'organizations', type_='unique')
    op.drop_column('organizations', 'url')
    op.drop_column('organizations', 'identification_number')
    op.drop_constraint('uq_membership_identity_org', 'memberships', type_='unique')
    op.drop_constraint('uq_identity_project_permission', 'identity_project_permissions', type_='unique')
    op.drop_index('uq_active_card_assignment', table_name='card_assignment_history', postgresql_where=sa.text('unassigned_at IS NULL'))
    # ### end Alembic commands ###
